In [1]:
import numpy as np

In [2]:
A = np.array([[0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0, 0, 0],
              [0, 0, 0, 0, 0, 0.3, 0, 0.7],
              [0, 0, 0.5, 0, 0, 0, 0.5, 0],
              [0, 0, 0, 0.8, 0, 0, 0.2, 0],
              [0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 1]])
print(A)

[[0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.3 0.  0.7]
 [0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.8 0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1. ]]


In [9]:
P = np.array([[0, 0, 0, 0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0],
              [1, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 1, 0, 0],
              [0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 1]])

print(P)

[[0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [10]:
A_new = np.dot(np.dot(P, A), np.linalg.inv(P))
print(A_new)

[[0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]
 [0.3 0.7 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.3 0.  0.7]
 [0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.8 0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1. ]]
