In [121]:
import numpy as np

In [122]:
P = np.array([[0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0, 0, 0],
              [0, 0, 0, 0, 0, 0.3, 0, 0.7],
              [0, 0, 0.5, 0, 0, 0, 0.5, 0],
              [0, 0, 0, 0.8, 0, 0, 0.2, 0],
              [0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 1]])

In [123]:
print(P)

[[0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.3 0.  0.7]
 [0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.8 0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1. ]]


In [124]:
X = np.array([[0, 0, 1, 0, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0],
              [0, 0, 0, 0, 0, 0.3],
              [0, 0, 0.5, 0, 0, 0],
              [0, 0, 0, 0.8, 0, 0]])

Y = np.array([[0, 0],
              [0, 0],
              [0, 0],
              [0, 0.7],
              [0.5, 0],
              [0.2, 0]])

Z = np.array([[1, 0],
              [0, 1]])

In [125]:
print(X)

[[0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0. ]
 [0.  0.  0.  0.  0.  0.3]
 [0.  0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.8 0.  0. ]]


In [126]:
print(np.power((np.eye(6) + X), 6))

[[1.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 1.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00]
 [0.00000e+00 1.17649e-01 1.00000e+00 0.00000e+00 7.29000e-04 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 7.29000e-04]
 [0.00000e+00 0.00000e+00 1.56250e-02 0.00000e+00 1.00000e+00 0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 2.62144e-01 0.00000e+00 1.00000e+00]]


In [127]:
print(Y)

[[0.  0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0.7]
 [0.5 0. ]
 [0.2 0. ]]


In [128]:
print(Z)

[[1 0]
 [0 1]]


In [129]:
P_hitting_prob = np.matmul(np.linalg.inv(np.eye(6) - X),Y)

In [130]:
print(P_hitting_prob)

[[0.24148607 0.75851393]
 [0.07894737 0.92105263]
 [0.24148607 0.75851393]
 [0.07894737 0.92105263]
 [0.62074303 0.37925697]
 [0.26315789 0.73684211]]


In [131]:
P_hitting_prob_rounded = np.round(P_hitting_prob, 2)
print(P_hitting_prob_rounded)

[[0.24 0.76]
 [0.08 0.92]
 [0.24 0.76]
 [0.08 0.92]
 [0.62 0.38]
 [0.26 0.74]]


In [132]:
e = np.ones((6, 1))
print(e)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [133]:
P_hitting_time = np.matmul(np.linalg.inv(np.eye(6) - X), e) 

In [134]:
print(P_hitting_time)

[[4.76160991]
 [2.71052632]
 [3.76160991]
 [1.71052632]
 [2.88080495]
 [2.36842105]]


In [135]:
P_hitting_time_rounded = np.round(P_hitting_time, 2)
print(P_hitting_time_rounded)

[[4.76]
 [2.71]
 [3.76]
 [1.71]
 [2.88]
 [2.37]]


In [136]:
X_e = np.array([[0, 0, 1, 0, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0],
              [0, 0, 0, 0, 0, 0.3],
              [0, 0, 0.5, 0, 0, 0],
              [0, 0, 0, 0.8, 0, 0]])

Y_e = np.array([[0],
              [0],
              [0],
              [0.7],
              [0],
              [0]])

Z_e = np.array([[1]])

In [137]:
print(X_e)

[[0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0. ]
 [0.  0.  0.  0.  0.  0.3]
 [0.  0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.8 0.  0. ]]


In [138]:
print(Y_e)

[[0. ]
 [0. ]
 [0. ]
 [0.7]
 [0. ]
 [0. ]]


In [139]:
print(Z_e)

[[1]]


In [140]:
P_e_hitting_time = np.matmul(np.linalg.inv(np.eye(6) - X_e), e)

In [141]:
print(P_e_hitting_time)

[[4.76160991]
 [2.71052632]
 [3.76160991]
 [1.71052632]
 [2.88080495]
 [2.36842105]]


# d)

In [142]:
N = np.linalg.inv(np.eye(6) - X_e)
print(N)

[[1.         0.82352941 1.17647059 1.08359133 0.35294118 0.3250774 ]
 [0.         1.         0.         1.31578947 0.         0.39473684]
 [0.         0.82352941 1.17647059 1.08359133 0.35294118 0.3250774 ]
 [0.         0.         0.         1.31578947 0.         0.39473684]
 [0.         0.41176471 0.58823529 0.54179567 1.17647059 0.1625387 ]
 [0.         0.         0.         1.05263158 0.         1.31578947]]


In [143]:
c = np.array([4,
              4,
              1,
              1,
              2,
              2])
print(c)

[4 4 1 1 2 2]


In [144]:
C_tot = np.dot(N,c)

In [145]:
print(C_tot)

[10.91021672  6.10526316  6.91021672  2.10526316  5.45510836  3.68421053]


# e)

In [146]:
X = np.array([
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0.7, 0, 0, 0.3, 0, 0, 0],
    [0, 0, 0, 0, 0, 0.3, 0, 0],
    [0, 0, 0.5, 0, 0, 0, 0.5, 0],
    [0, 0, 0, 0.8, 0, 0, 0, 0.2],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0]
])

print(X)

[[0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.3 0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.8 0.  0.  0.  0.2]
 [0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]]


In [147]:
N = np.linalg.inv(np.eye(8) - X)
print(N)

[[1.         1.         1.42857143 1.42857143 0.42857143 0.42857143
  0.21428571 0.08571429]
 [0.         1.         0.         1.42857143 0.         0.42857143
  0.         0.08571429]
 [0.         1.         1.42857143 1.42857143 0.42857143 0.42857143
  0.21428571 0.08571429]
 [0.         0.         0.         1.42857143 0.         0.42857143
  0.         0.08571429]
 [0.         1.         1.42857143 1.42857143 1.42857143 0.42857143
  0.71428571 0.08571429]
 [0.         0.         0.         1.42857143 0.         1.42857143
  0.         0.28571429]
 [0.         1.         1.42857143 1.42857143 0.42857143 0.42857143
  1.21428571 0.08571429]
 [0.         0.         0.         1.42857143 0.         0.42857143
  0.         1.08571429]]


In [148]:
print(N[0,6] + N[0,7])

0.30000000000000004


In [149]:
c = np.array([4,
              4,
              1,
              1,
              2,
              2,
              4,
              4])
print(c)

[4 4 1 1 2 2 4 4]


In [150]:
C_tot = np.dot(N,c)
print(C_tot)

[13.77142857  6.62857143  9.77142857  2.62857143 13.77142857  5.42857143
 13.77142857  6.62857143]
