In [2]:
import numpy as np

In [3]:
P = np.array([[0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0, 0, 0],
              [0, 0, 0, 0, 0, 0.3, 0, 0.7],
              [0, 0, 0.5, 0, 0, 0, 0.5, 0],
              [0, 0, 0, 0.8, 0, 0, 0.2, 0],
              [0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 1]])

In [4]:
print(P)

[[0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.3 0.  0.7]
 [0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.8 0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1. ]]


In [5]:
X = np.array([[0, 0, 1, 0, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0],
              [0, 0, 0, 0, 0, 0.3],
              [0, 0, 0.5, 0, 0, 0],
              [0, 0, 0, 0.8, 0, 0]])

Y = np.array([[0, 0],
              [0, 0],
              [0, 0],
              [0, 0.7],
              [0.5, 0],
              [0.2, 0]])

Z = np.array([[1, 0],
              [0, 1]])

In [6]:
print(X)

[[0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0. ]
 [0.  0.  0.  0.  0.  0.3]
 [0.  0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.8 0.  0. ]]


In [7]:
print(Y)

[[0.  0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0.7]
 [0.5 0. ]
 [0.2 0. ]]


In [8]:
print(Z)

[[1 0]
 [0 1]]


In [9]:
P_hitting_prob = np.matmul(np.linalg.inv(np.eye(6) - X),Y)

In [10]:
print(P_hitting_prob)

[[0.24148607 0.75851393]
 [0.07894737 0.92105263]
 [0.24148607 0.75851393]
 [0.07894737 0.92105263]
 [0.62074303 0.37925697]
 [0.26315789 0.73684211]]


In [11]:
P_hitting_prob_rounded = np.round(P_hitting_prob, 2)
print(P_hitting_prob_rounded)

[[0.24 0.76]
 [0.08 0.92]
 [0.24 0.76]
 [0.08 0.92]
 [0.62 0.38]
 [0.26 0.74]]


In [12]:
e = np.ones((6, 1))
print(e)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [13]:
P_hitting_time = np.matmul(np.linalg.inv(np.eye(6) - X), e) 

In [14]:
print(P_hitting_time)

[[4.76160991]
 [2.71052632]
 [3.76160991]
 [1.71052632]
 [2.88080495]
 [2.36842105]]


In [15]:
P_hitting_time_rounded = np.round(P_hitting_time, 2)
print(P_hitting_time_rounded)

[[4.76]
 [2.71]
 [3.76]
 [1.71]
 [2.88]
 [2.37]]


In [16]:
X_e = np.array([[0, 0, 1, 0, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0],
              [0, 0, 0, 0, 0, 0.3],
              [0, 0, 0.5, 0, 0, 0],
              [0, 0, 0, 0.8, 0, 0]])

Y_e = np.array([[0],
              [0],
              [0],
              [0.7],
              [0],
              [0]])

Z_e = np.array([[1]])

In [17]:
print(X_e)

[[0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0. ]
 [0.  0.  0.  0.  0.  0.3]
 [0.  0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.8 0.  0. ]]


In [18]:
print(Y_e)

[[0. ]
 [0. ]
 [0. ]
 [0.7]
 [0. ]
 [0. ]]


In [19]:
print(Z_e)

[[1]]


In [20]:
P_e_hitting_time = np.matmul(np.linalg.inv(np.eye(6) - X_e), e)

In [21]:
print(P_e_hitting_time)

[[4.76160991]
 [2.71052632]
 [3.76160991]
 [1.71052632]
 [2.88080495]
 [2.36842105]]
