In [1]:
import numpy as np

In [2]:
P = np.array([[0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0, 0, 0],
              [0, 0, 0, 0, 0, 0.3, 0, 0.7],
              [0, 0, 0.5, 0, 0, 0, 0.5, 0],
              [0, 0, 0, 0.8, 0, 0, 0.2, 0],
              [0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 1]])

In [3]:
print(P)

In [4]:
X = np.array([[0, 0, 1, 0, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0],
              [0, 0, 0, 0, 0, 0.3],
              [0, 0, 0.5, 0, 0, 0],
              [0, 0, 0, 0.8, 0, 0]])

Y = np.array([[0, 0],
              [0, 0],
              [0, 0],
              [0, 0.7],
              [0.5, 0],
              [0.2, 0]])

Z = np.array([[1, 0],
              [0, 1]])

In [5]:
print(X)

[[0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0. ]
 [0.  0.  0.  0.  0.  0.3]
 [0.  0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.8 0.  0. ]]


In [6]:
print(Y)

[[0.  0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0.7]
 [0.5 0. ]
 [0.2 0. ]]


In [7]:
print(Z)

[[1 0]
 [0 1]]


In [8]:
P_hitting_prob = np.matmul(np.linalg.inv(np.eye(6) - X),Y)

In [9]:
print(P_hitting_prob)

[[0.24148607 0.75851393]
 [0.07894737 0.92105263]
 [0.24148607 0.75851393]
 [0.07894737 0.92105263]
 [0.62074303 0.37925697]
 [0.26315789 0.73684211]]


In [10]:
P_hitting_prob_rounded = np.round(P_hitting_prob, 2)
print(P_hitting_prob_rounded)

[[0.24 0.76]
 [0.08 0.92]
 [0.24 0.76]
 [0.08 0.92]
 [0.62 0.38]
 [0.26 0.74]]


In [11]:
e = np.ones((6, 1))
print(e)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [12]:
P_hitting_time = np.matmul(np.linalg.inv(np.eye(6) - X), e) 

In [13]:
print(P_hitting_time)

[[4.76160991]
 [2.71052632]
 [3.76160991]
 [1.71052632]
 [2.88080495]
 [2.36842105]]


In [14]:
P_hitting_time_rounded = np.round(P_hitting_time, 2)
print(P_hitting_time_rounded)

[[4.76]
 [2.71]
 [3.76]
 [1.71]
 [2.88]
 [2.37]]


In [15]:
X_e = np.array([[0, 0, 1, 0, 0, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0],
              [0, 0, 0, 0, 0, 0.3],
              [0, 0, 0.5, 0, 0, 0],
              [0, 0, 0, 0.8, 0, 0]])

Y_e = np.array([[0],
              [0],
              [0],
              [0.7],
              [0],
              [0]])

Z_e = np.array([[1]])

In [16]:
print(X_e)

[[0.  0.  1.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0. ]
 [0.  0.  0.  0.  0.  0.3]
 [0.  0.  0.5 0.  0.  0. ]
 [0.  0.  0.  0.8 0.  0. ]]


In [17]:
print(Y_e)

[[0. ]
 [0. ]
 [0. ]
 [0.7]
 [0. ]
 [0. ]]


In [18]:
print(Z_e)

[[1]]


In [19]:
P_e_hitting_time = np.matmul(np.linalg.inv(np.eye(6) - X_e), e)

In [20]:
print(P_e_hitting_time)

[[4.76160991]
 [2.71052632]
 [3.76160991]
 [1.71052632]
 [2.88080495]
 [2.36842105]]


# d)

In [21]:
N = np.linalg.inv(np.eye(6) - X_e)
print(N)

[[1.         0.82352941 1.17647059 1.08359133 0.35294118 0.3250774 ]
 [0.         1.         0.         1.31578947 0.         0.39473684]
 [0.         0.82352941 1.17647059 1.08359133 0.35294118 0.3250774 ]
 [0.         0.         0.         1.31578947 0.         0.39473684]
 [0.         0.41176471 0.58823529 0.54179567 1.17647059 0.1625387 ]
 [0.         0.         0.         1.05263158 0.         1.31578947]]


In [24]:
c = np.array([4,
              4,
              1,
              1,
              2,
              2])
print(c)

[4 4 1 1 2 2]


In [25]:
C_tot = np.dot(N,c)

In [26]:
print(C_tot)

[10.91021672  6.10526316  6.91021672  2.10526316  5.45510836  3.68421053]


# e)

In [32]:
X = np.array([
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0.7, 0, 0, 0.3, 0, 0, 0],
    [0, 0, 0, 0, 0, 0.3, 0, 0],
    [0, 0, 0.5, 0, 0, 0, 0.5, 0],
    [0, 0, 0, 0.8, 0, 0, 0, 0.2],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0]
])

print(X)

[[0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.3 0.  0. ]
 [0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.8 0.  0.  0.  0.2]
 [0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]]


In [33]:
N = np.linalg.inv(np.eye(8) - X)
print(N)

[[1.         1.         1.42857143 1.42857143 0.42857143 0.42857143
  0.21428571 0.08571429]
 [0.         1.         0.         1.42857143 0.         0.42857143
  0.         0.08571429]
 [0.         1.         1.42857143 1.42857143 0.42857143 0.42857143
  0.21428571 0.08571429]
 [0.         0.         0.         1.42857143 0.         0.42857143
  0.         0.08571429]
 [0.         1.         1.42857143 1.42857143 1.42857143 0.42857143
  0.71428571 0.08571429]
 [0.         0.         0.         1.42857143 0.         1.42857143
  0.         0.28571429]
 [0.         1.         1.42857143 1.42857143 0.42857143 0.42857143
  1.21428571 0.08571429]
 [0.         0.         0.         1.42857143 0.         0.42857143
  0.         1.08571429]]


In [36]:
print(N[0,6] + N[0,7])

0.30000000000000004


In [34]:
c = np.array([4,
              4,
              1,
              1,
              2,
              2,
              4,
              4])
print(c)

[4 4 1 1 2 2 4 4]


In [35]:
C_tot = np.dot(N,c)
print(C_tot)

[13.77142857  6.62857143  9.77142857  2.62857143 13.77142857  5.42857143
 13.77142857  6.62857143]
