In [1]:
import numpy as np

In [13]:
A = np.array([[0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0.7, 0, 0, 0.3, 0, 0, 0],
              [0, 0, 0, 0, 0, 0.3, 0, 0.7],
              [0, 0, 0.5, 0, 0, 0, 0.5, 0],
              [0, 0, 0, 0.8, 0, 0, 0.2, 0],
              [0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 1]])

print(A)

[[0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.7 0.  0.  0.3 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.3 0.  0.7]
 [0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.8 0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1. ]]


In [17]:
P_1 = np.array([[0, 0, 0, 0, 0, 1, 0, 0],
                [0, 0, 0, 0, 1, 0, 0, 0],
                [0, 0, 1, 0, 0, 0, 0, 0],
                [0, 0, 0, 1, 0, 0, 0, 0],
                [0, 1, 0, 0, 0, 0, 0, 0],
                [1, 0, 0, 0, 0, 0, 0, 0], 
                [0, 0, 0, 0, 0, 0, 1, 0], 
                [0, 0, 0, 0, 0, 0, 0, 1]])

print(P_1)

[[0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [18]:
P_1A = np.matmul(P_1, A)
P_1AP_1T = np.matmul(P_1A,P_1.T)

print(P_1AP_1T)

[[0.  0.  0.  0.8 0.  0.  0.2 0. ]
 [0.  0.  0.5 0.  0.  0.  0.5 0. ]
 [0.  0.3 0.  0.  0.7 0.  0.  0. ]
 [0.3 0.  0.  0.  0.  0.  0.  0.7]
 [0.  0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1. ]]


In [19]:
P_2 = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                [0, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 0, 0],
                [0, 0, 1, 0, 0, 0, 0, 0],
                [0, 0, 0, 1, 0, 0, 0, 0], 
                [0, 0, 0, 0, 0, 0, 1, 0], 
                [0, 0, 0, 0, 0, 0, 0, 1]])

print(P_2)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [20]:
P_2A = np.matmul(P_2, P_1AP_1T)
P_2AP_2T = np.matmul(P_2A,P_2.T)

print(P_2AP_2T)

[[0.  0.  0.  0.  0.  0.8 0.2 0. ]
 [0.  0.  0.  0.  0.5 0.  0.5 0. ]
 [0.  0.  0.  0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  1.  0.  0.  0. ]
 [0.  0.3 0.7 0.  0.  0.  0.  0. ]
 [0.3 0.  0.  0.  0.  0.  0.  0.7]
 [0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1. ]]


In [23]:
P_3 = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                [0, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 0, 0],
                [0, 0, 0, 0, 1, 0, 0, 0],
                [0, 0, 0, 1, 0, 0, 0, 0],
                [0, 0, 1, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 1]])

print(P_3)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [24]:
P_3A = np.matmul(P_3, P_2AP_2T)
P_3AP_3T = np.matmul(P_3A,P_3.T)

print(P_3AP_3T)

[[0.  0.  0.8 0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.5 0.  0.  0.5 0. ]
 [0.3 0.  0.  0.  0.  0.  0.  0.7]
 [0.  0.3 0.  0.  0.  0.7 0.  0. ]
 [0.  0.  0.  1.  0.  0.  0.  0. ]
 [0.  0.  1.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1. ]]
