In [2]:
import numpy as np

In [7]:
A = np.array([[4, -1, -2],
              [-1, 4, -2],
              [-2, -2, 5]])
A

array([[ 4, -1, -2],
       [-1,  4, -2],
       [-2, -2,  5]])

In [6]:
G = np.linalg.cholesky(A)
G

array([[ 2.        ,  0.        ,  0.        ],
       [-0.5       ,  1.93649167,  0.        ],
       [-1.        , -1.29099445,  1.52752523]])

In [9]:
y = np.array([[1],
              [-3],
              [2]])
y

array([[ 1],
       [-3],
       [ 2]])

In [10]:
z = np.linalg.solve(G, y)
z

array([[ 0.5       ],
       [-1.42009389],
       [ 0.43643578]])

In [15]:
x = np.linalg.solve(G.T, z)
x

array([[ 0.25714286],
       [-0.54285714],
       [ 0.28571429]])

In [16]:
x_control = np.linalg.solve(A, y)
x_control

array([[ 0.25714286],
       [-0.54285714],
       [ 0.28571429]])