In [2]:
import numpy as np

In [6]:
x_0 = np.array([[1],
              [0],
              [0],
              [0]])

B = np.array([[0, 1/2, 0, 1/2],
              [0, 0.4, 0.6, 0],
              [0, 0, 0.4, 0.6],
              [0.4, 0, 0, 0.6]])

In [14]:
x_0

array([[1],
       [0],
       [0],
       [0]])

In [7]:
B_power_of_4 = np.linalg.matrix_power(B, 4)
B_power_of_4

array([[0.184 , 0.132 , 0.204 , 0.48  ],
       [0.2016, 0.0976, 0.1536, 0.5472],
       [0.2304, 0.168 , 0.0976, 0.504 ],
       [0.1824, 0.192 , 0.168 , 0.4576]])

In [13]:
x_4 = np.dot(x_0.T, B_power_of_4)
x_4

array([[0.184, 0.132, 0.204, 0.48 ]])